### ISSUE TITLE
Error when deploying in another namespace

### ISSUE THREAD

**Issue by ieugen** [stakater/ProxyInjector#28]
Hello, 

It seems that deploying in another namespace does not work:

````
 kubectl delete -f https://raw.githubusercontent.com/stakater/ProxyInjector/master/deployments/kubernetes/proxyinjector.yaml -n infra
```

Gives this
```
✗ k get pods 
NAME                             READY   STATUS             RESTARTS   AGE
proxyinjector-599674c9bf-qzq88   0/1     CrashLoopBackOff   3          92s


➜ configs git:(develop) ✗ k logs -f proxyinjector-599674c9bf-qzq88 
time="2019-07-17T16:04:01Z" level=info msg="Starting ProxyInjector"
time="2019-07-17T16:04:01Z" level=warning msg="KUBERNETES_NAMESPACE is unset, will detect changes in all namespaces."
2019/07/17 16:04:01 Reading YAML Configuration
2019/07/17 16:04:01 open config.yaml: no such file or directory
panic: open config.yaml: no such file or directory

goroutine 1 [running]:
log.Panic(0xc420139990, 0x1, 0x1)
	/usr/local/go/src/log/log.go:326 +0xc0
github.com/stakater/ProxyInjector/internal/pkg/config.ReadConfig(0x108cd6d, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/stakater/ProxyInjector/internal/pkg/config/config.go:35 +0x14a
github.com/stakater/ProxyInjector/internal/pkg/config.GetControllerConfig(0xc4203ffd40, 0x0, 0x0)
	/go/src/github.com/stakater/ProxyInjector/internal/pkg/config/config.go:53 +0x74
github.com/stakater/ProxyInjector/internal/pkg/cmd.startProxyInjector(0xc420287400, 0x1824a20, 0x0, 0x0)
	/go/src/github.com/stakater/ProxyInjector/internal/pkg/cmd/proxyinjector.go:38 +0x13a
github.com/stakater/ProxyInjector/vendor/github.com/spf13/cobra.(*Command).execute(0xc420287400, 0xc42000e180, 0x0, 0x0, 0xc420287400, 0xc42000e180)
	/go/src/github.com/stakater/ProxyInjector/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/stakater/ProxyInjector/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420287400, 0x1085f60, 0xe74401, 0xc420287400)
	/go/src/github.com/stakater/ProxyInjector/vendor/github.com/spf13/cobra/command.go:852 +0x334
github.com/stakater/ProxyInjector/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420287400, 0xc420287400, 0xe7c966)
	/go/src/github.com/stakater/ProxyInjector/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/stakater/ProxyInjector/internal/pkg/app.Run(0xc420139f70, 0xe7d1a9)
	/go/src/github.com/stakater/ProxyInjector/internal/pkg/app/app.go:8 +0x9a
```

**Comment by usamaahmadkhan** [comment]
Hi, @ieugen the manifest you are trying to deploy has `default` and `test-proxyinjector` namespaces set for testing purposes. You need to edit it according to your namespace before applying via kubectl. Hope this solves your problem.

**Comment by ieugen** [comment]
Thanks. I probably should hqve checked that. I got confused since I had to specify the namespace in the command line. I imagine that it takes precedence.

Maybe droping the namespaces from the file and keeping them in the cli is a good idea ?

**Comment by usamaahmadkhan** [comment]
The manifest is generic. Depends upon the use case e.g. someone does not want to remember providing namespace with the `kubectl apply` command everytime.
